package main

import (
	"log"
	"os"
	"strings"
)

//go:generate go run genconstants.go "Version" "1.2.3" "Name" "myapp" "Title" "My Application"

type constDecl struct {
	Name string
	Val  string
}

func main() {
	//Допишите код
	f, err := os.OpenFile("generated.go", os.O_CREATE|os.O_WRONLY, os.ModePerm)
	if err != nil {
		log.Fatalf("Cant create a file, err: %v", err)
	}
	defer f.Close()

	consts := make([]constDecl, 0)

	for i, c := range os.Args[1:] {
		if i%2 == 0 {
			consts = append(consts, constDecl{
				Name: c,
			})
		} else {
			consts[len(consts)-1].Val = c
		}
	}

	strBuilder := strings.Builder{}
	strBuilder.WriteString("// Constants in this code were generated by go generate; DO NOT EDIT.\n")
	strBuilder.WriteString("// This file was generated by genconstants.go\n")
	strBuilder.WriteString("package main\n\n")
	strBuilder.WriteString("const(\n")
	for _, c := range consts {
		strBuilder.WriteString("\t")
		strBuilder.WriteString(c.Name)
		strBuilder.WriteString(" = \"")
		strBuilder.WriteString(c.Val)
		strBuilder.WriteString("\"\n")
	}
	strBuilder.WriteString(")\n")

	_, err = f.Write([]byte(strBuilder.String()))
	if err != nil {
		log.Fatalf("Cant write to a file, err: %v", err)
	}
}
